"""empty message

Revision ID: 282b3dd63555
Revises: bfab7777f412
Create Date: 2020-11-04 17:15:59.142304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '282b3dd63555'
down_revision = 'bfab7777f412'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('created_at', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'created_at')
    # ### end Alembic commands ###
